name: Daily M3U8 Grabber

on:
  workflow_dispatch:


jobs:
  DAILY_m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: âš™ï¸ Setup Python
        run: |
          sudo apt update -y
          pip install requests

      - name: ðŸ“„ Ambil daylidata.txt dari Repo Privat
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} private
          cp private/daylidata.txt $HOME/daylidata.txt
          rm -rf private

      - name: â–¶ï¸ Jalankan Python Grabber
        run: |
          python getdaily.py

      - name: âœ… Commit & Push hasil
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          
          # Pastikan branch utama sinkron
          git pull origin master || git pull origin main || true

          # Tambahkan semua file hasil (*.txt)
          git add *.txt || true

          if git diff --cached --quiet; then
            echo "âš ï¸ Tidak ada perubahan file M3U8"
          else
            TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
            echo "Run at: ${TIMESTAMP}" > .last_run_daily
            git add .last_run_daily

            git commit -m "ðŸ†• Update M3U8 hasil Dailymotion - ${TIMESTAMP}"
            git push origin HEAD:master || git push origin HEAD:main
            echo "âœ… Commit berhasil pada ${TIMESTAMP}"
          fi
